name: task_list_app
description: Task list application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.1.3
  flutter_slider_drawer: ^2.1.3
  go_router: ^9.0.0
  hooks_riverpod: ^2.1.3
  json_annotation: ^4.8.1
  riverpod: ^2.3.6

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0

flutter:
  uses-material-design: true
